# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Lint and test

on:
  pull_request:
    branches:
      - master
  push:
    branches: 
      - master

jobs:
  test_and_lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'test_and_lint'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test with pytest
        run: |
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
          pytest

# Cancel previous in-progress when pushing: https://stackoverflow.com/a/72408109
concurrency:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
